// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzR2GOTVcJvRQdW5z9d0W63CXMQ3BFZgQ',
    appId: '1:508955945769:web:5508c11e8fb66cdb036538',
    messagingSenderId: '508955945769',
    projectId: 'projec-all',
    authDomain: 'projec-all.firebaseapp.com',
    storageBucket: 'projec-all.appspot.com',
    measurementId: 'G-HJXF281RML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf0oXEWexOKUUWl2cqePBXMww-V31Rki4',
    appId: '1:508955945769:android:3217468bdaf7b438036538',
    messagingSenderId: '508955945769',
    projectId: 'projec-all',
    storageBucket: 'projec-all.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfvrCptiqxTlROVFqb7qk2id6RkGljlWw',
    appId: '1:508955945769:ios:805c54c6849edfa3036538',
    messagingSenderId: '508955945769',
    projectId: 'projec-all',
    storageBucket: 'projec-all.appspot.com',
    iosBundleId: 'com.example.projects',
  );
}
